auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Julong's Lab
url:              http://www.julong.tk
feed:             /atom.xml
author:
    name:         Julong
    twitter:      twitter.com/eategg
description:      "Julong\'s Blog"
author_info:      <a href="http://www.julong.tk/about">Julong</a>

copyright:
    - Julong.Tk
